# Generated by Django 5.1.5 on 2025-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postmedia_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='community_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
