# Generated by Django 5.1.5 on 2025-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_posts_community_id_alter_posts_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('community', 'Community')], default='personal', max_length=10),
        ),
    ]
