# Generated by Django 5.1.5 on 2025-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_posts_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_type',
        ),
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
