# Generated by Django 5.1.5 on 2025-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_posts_community_id_remove_posts_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='community_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='posts',
            name='privacy',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
