# Generated by Django 5.1.5 on 2025-03-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_posts_community_id_posts_post_type_posts_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='privacy',
        ),
    ]
