# Generated by Django 5.1.5 on 2025-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_posts_community_id_remove_posts_post_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reporter_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Content_Reports',
            },
        ),
    ]
