# Generated by Django 5.1.5 on 2025-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_contentreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='community_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('general', 'General'), ('community', 'Community')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='posts',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
