# Generated by Django 5.1.5 on 2025-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_posts_community_id_posts_post_type_posts_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('post_hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('hashtag_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_hashtags',
                'unique_together': {('post_id', 'hashtag_id')},
            },
        ),
    ]
